name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        features:
          - bundled
          - bundled,serde,strum
          # experimental-aec3-config implicitly activates bundled (build would fail if it doesn't)
          - experimental-aec3-config,schemars,serde,strum

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Dependencies (if Ubuntu)
        env:
          ACCEPT_EULA: Y
        run: sudo apt-get -y update && sudo apt-get install -f && sudo apt-get -y install pkg-config meson ninja-build
        if: contains(runner.os, 'Linux')
      - name: Install Dependencies (if macos)
        env:
          ACCEPT_EULA: Y
        run: brew update && brew install pkg-config meson ninja
        if: contains(runner.os, 'macOS')
      - uses: Swatinem/rust-cache@v1
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features "${{ matrix.features }}" --all-targets -- -D warnings
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --features "${{ matrix.features }}"
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          # we have tests even in examples, --all-targets ensures they are run
          args: --verbose --features "${{ matrix.features }}" --all-targets

  test-non-bundled:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - schemars,serde

    steps:
      - uses: actions/checkout@v2
        # No need for submodules here
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install System Dependencies
        env:
          ACCEPT_EULA: Y
        run: sudo apt-get -y update && sudo apt-get install -f && sudo apt-get -y install pkg-config meson ninja-build
      - name: Compile webrtc-audio-processing 2.1 library manually
        run: |
          git clone --branch v2.1 https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing.git
          cd webrtc-audio-processing
          meson setup build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
      - uses: Swatinem/rust-cache@v1
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features "${{ matrix.features }}" --all-targets -- -D warnings
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --features "${{ matrix.features }}"
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features "${{ matrix.features }}"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: clang-format
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: 13
          check-path: webrtc-audio-processing-sys/src
          fallback-style: Chromium
